name: golangci
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go from go.mod
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          go build -v ./...
          
      - name: Test with the Go CLI
        run: go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 5m
