name: golangci
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        go-version: ["1.23"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - uses: actions/checkout@v3
      - name: Build
        run: |
          go get -d -v
          go build -v .
          
      - name: Test with the Go CLI
        run: go test -v .

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m
