name: golangci
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19"]
    defaults:
      run:
        shell: bash
        #working-directory: src
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
        id: go

      - uses: actions/checkout@v3
      - name: Build
        run: |
          go get -d -v
          go build -v .
          
      - name: Test with the Go CLI
        run: go test -v .
