name: golangci-lint

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m
